In [11]:
from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import json

# This secure connect bundle is autogenerated when you donwload your SCB, 
# if yours is different update the file name below
cloud_config= {
  'secure_connect_bundle': 'C:/Users/Admin/Downloads/secure-connect-test-rahul.zip'
}

auth_provider = PlainTextAuthProvider("vUWYgZMnZkFhjDGZXoKJRbXw", "wvkKTzlNB,ddGHiJ,utUq33oLhZgnWX2-9aJcNzAv4fD62m8yBP4c,R43K6ZB.X8ZZzmMMFrBncmXUNBy_l+RiAswxl31FnwZIk4iT2DabPGUBbNu2LIsGTC6kZ2.No7")
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect("sudhadb")

row = session.execute("select release_version from system.local").one()
if row:
  print(row[0])
else:
  print("An error occurred.")

4.0.0.6816

In [12]:
session.execute("create table employee(emp_id int, name text, age int, salary int,primary key(emp_id))")

In [15]:
session.execute("insert into employee (emp_id,name,age,salary) values (1,'Sudha',63,56666)")

In [17]:
session.execute("insert into employee (emp_id,name,age,salary) values (2,'Rahul',36,56666)")

In [18]:
session.execute("insert into employee (emp_id,name,age,salary) values (3,'Komal',26,26666)")

In [20]:
session.execute("insert into employee (emp_id,name,age,salary) values (4,'Chhoti',33,36666)")

In [21]:
for i in session.execute("select * from employee"):
    print(i)

Row(emp_id=1, age=63, name='Sudha', salary=56666)
Row(emp_id=2, age=36, name='Rahul', salary=56666)
Row(emp_id=4, age=33, name='Chhoti', salary=36666)
Row(emp_id=3, age=26, name='Komal', salary=26666)